<?php


/**
 * Skeleton subclass for performing query and update operations on the 'categories' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 05/08/10 14:58:12
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CategoriesPeer extends BaseCategoriesPeer {

} // CategoriesPeer
