<?php

/**
 * Base class that represents a row from the 'advice' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 05/09/10 07:49:06
 *
 * @package    lib.model.om
 */
abstract class BaseAdvice extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AdvicePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the slug field.
	 * @var        string
	 */
	protected $slug;

	/**
	 * The value for the rating field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $rating;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the instruction field.
	 * @var        string
	 */
	protected $instruction;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the active field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $active;

	/**
	 * The value for the movie field.
	 * @var        string
	 */
	protected $movie;

	/**
	 * The value for the level field.
	 * @var        int
	 */
	protected $level;

	/**
	 * The value for the visited field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $visited;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the category_id field.
	 * @var        int
	 */
	protected $category_id;

	/**
	 * The value for the category_upcategory_id field.
	 * @var        int
	 */
	protected $category_upcategory_id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * @var        Categories
	 */
	protected $aCategoriesRelatedByCategoryId;

	/**
	 * @var        Categories
	 */
	protected $aCategoriesRelatedByCategoryUpcategoryId;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUser;

	/**
	 * @var        array Tags[] Collection to store aggregation of Tags objects.
	 */
	protected $collTagss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTagss.
	 */
	private $lastTagsCriteria = null;

	/**
	 * @var        array Images[] Collection to store aggregation of Images objects.
	 */
	protected $collImagess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collImagess.
	 */
	private $lastImagesCriteria = null;

	/**
	 * @var        array Comments[] Collection to store aggregation of Comments objects.
	 */
	protected $collCommentss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCommentss.
	 */
	private $lastCommentsCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'AdvicePeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->rating = 0;
		$this->active = false;
		$this->visited = 1;
	}

	/**
	 * Initializes internal state of BaseAdvice object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [slug] column value.
	 * 
	 * @return     string
	 */
	public function getSlug()
	{
		return $this->slug;
	}

	/**
	 * Get the [rating] column value.
	 * 
	 * @return     int
	 */
	public function getRating()
	{
		return $this->rating;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [instruction] column value.
	 * 
	 * @return     string
	 */
	public function getInstruction()
	{
		return $this->instruction;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [active] column value.
	 * 
	 * @return     boolean
	 */
	public function getActive()
	{
		return $this->active;
	}

	/**
	 * Get the [movie] column value.
	 * 
	 * @return     string
	 */
	public function getMovie()
	{
		return $this->movie;
	}

	/**
	 * Get the [level] column value.
	 * 
	 * @return     int
	 */
	public function getLevel()
	{
		return $this->level;
	}

	/**
	 * Get the [visited] column value.
	 * 
	 * @return     int
	 */
	public function getVisited()
	{
		return $this->visited;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [category_id] column value.
	 * 
	 * @return     int
	 */
	public function getCategoryId()
	{
		return $this->category_id;
	}

	/**
	 * Get the [category_upcategory_id] column value.
	 * 
	 * @return     int
	 */
	public function getCategoryUpcategoryId()
	{
		return $this->category_upcategory_id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = AdvicePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [slug] column.
	 * 
	 * @param      string $v new value
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setSlug($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->slug !== $v) {
			$this->slug = $v;
			$this->modifiedColumns[] = AdvicePeer::SLUG;
		}

		return $this;
	} // setSlug()

	/**
	 * Set the value of [rating] column.
	 * 
	 * @param      int $v new value
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setRating($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rating !== $v || $this->isNew()) {
			$this->rating = $v;
			$this->modifiedColumns[] = AdvicePeer::RATING;
		}

		return $this;
	} // setRating()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = AdvicePeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Set the value of [instruction] column.
	 * 
	 * @param      string $v new value
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setInstruction($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->instruction !== $v) {
			$this->instruction = $v;
			$this->modifiedColumns[] = AdvicePeer::INSTRUCTION;
		}

		return $this;
	} // setInstruction()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AdvicePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Set the value of [active] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setActive($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->active !== $v || $this->isNew()) {
			$this->active = $v;
			$this->modifiedColumns[] = AdvicePeer::ACTIVE;
		}

		return $this;
	} // setActive()

	/**
	 * Set the value of [movie] column.
	 * 
	 * @param      string $v new value
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setMovie($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->movie !== $v) {
			$this->movie = $v;
			$this->modifiedColumns[] = AdvicePeer::MOVIE;
		}

		return $this;
	} // setMovie()

	/**
	 * Set the value of [level] column.
	 * 
	 * @param      int $v new value
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setLevel($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->level !== $v) {
			$this->level = $v;
			$this->modifiedColumns[] = AdvicePeer::LEVEL;
		}

		return $this;
	} // setLevel()

	/**
	 * Set the value of [visited] column.
	 * 
	 * @param      int $v new value
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setVisited($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->visited !== $v || $this->isNew()) {
			$this->visited = $v;
			$this->modifiedColumns[] = AdvicePeer::VISITED;
		}

		return $this;
	} // setVisited()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = AdvicePeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Set the value of [category_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setCategoryId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->category_id !== $v) {
			$this->category_id = $v;
			$this->modifiedColumns[] = AdvicePeer::CATEGORY_ID;
		}

		if ($this->aCategoriesRelatedByCategoryId !== null && $this->aCategoriesRelatedByCategoryId->getId() !== $v) {
			$this->aCategoriesRelatedByCategoryId = null;
		}

		return $this;
	} // setCategoryId()

	/**
	 * Set the value of [category_upcategory_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setCategoryUpcategoryId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->category_upcategory_id !== $v) {
			$this->category_upcategory_id = $v;
			$this->modifiedColumns[] = AdvicePeer::CATEGORY_UPCATEGORY_ID;
		}

		if ($this->aCategoriesRelatedByCategoryUpcategoryId !== null && $this->aCategoriesRelatedByCategoryUpcategoryId->getCategoryupId() !== $v) {
			$this->aCategoriesRelatedByCategoryUpcategoryId = null;
		}

		return $this;
	} // setCategoryUpcategoryId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Advice The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = AdvicePeer::USER_ID;
		}

		if ($this->asfGuardUser !== null && $this->asfGuardUser->getId() !== $v) {
			$this->asfGuardUser = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->rating !== 0) {
				return false;
			}

			if ($this->active !== false) {
				return false;
			}

			if ($this->visited !== 1) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->slug = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->rating = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->description = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->instruction = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->created_at = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->active = ($row[$startcol + 6] !== null) ? (boolean) $row[$startcol + 6] : null;
			$this->movie = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->level = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->visited = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->title = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->category_id = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->category_upcategory_id = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->user_id = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 14; // 14 = AdvicePeer::NUM_COLUMNS - AdvicePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Advice object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aCategoriesRelatedByCategoryId !== null && $this->category_id !== $this->aCategoriesRelatedByCategoryId->getId()) {
			$this->aCategoriesRelatedByCategoryId = null;
		}
		if ($this->aCategoriesRelatedByCategoryUpcategoryId !== null && $this->category_upcategory_id !== $this->aCategoriesRelatedByCategoryUpcategoryId->getCategoryupId()) {
			$this->aCategoriesRelatedByCategoryUpcategoryId = null;
		}
		if ($this->asfGuardUser !== null && $this->user_id !== $this->asfGuardUser->getId()) {
			$this->asfGuardUser = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AdvicePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AdvicePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aCategoriesRelatedByCategoryId = null;
			$this->aCategoriesRelatedByCategoryUpcategoryId = null;
			$this->asfGuardUser = null;
			$this->collTagss = null;
			$this->lastTagsCriteria = null;

			$this->collImagess = null;
			$this->lastImagesCriteria = null;

			$this->collCommentss = null;
			$this->lastCommentsCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AdvicePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAdvice:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				AdvicePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAdvice:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AdvicePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAdvice:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			
			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(AdvicePeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAdvice:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				AdvicePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCategoriesRelatedByCategoryId !== null) {
				if ($this->aCategoriesRelatedByCategoryId->isModified() || $this->aCategoriesRelatedByCategoryId->isNew()) {
					$affectedRows += $this->aCategoriesRelatedByCategoryId->save($con);
				}
				$this->setCategoriesRelatedByCategoryId($this->aCategoriesRelatedByCategoryId);
			}

			if ($this->aCategoriesRelatedByCategoryUpcategoryId !== null) {
				if ($this->aCategoriesRelatedByCategoryUpcategoryId->isModified() || $this->aCategoriesRelatedByCategoryUpcategoryId->isNew()) {
					$affectedRows += $this->aCategoriesRelatedByCategoryUpcategoryId->save($con);
				}
				$this->setCategoriesRelatedByCategoryUpcategoryId($this->aCategoriesRelatedByCategoryUpcategoryId);
			}

			if ($this->asfGuardUser !== null) {
				if ($this->asfGuardUser->isModified() || $this->asfGuardUser->isNew()) {
					$affectedRows += $this->asfGuardUser->save($con);
				}
				$this->setsfGuardUser($this->asfGuardUser);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AdvicePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AdvicePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AdvicePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collTagss !== null) {
				foreach ($this->collTagss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collImagess !== null) {
				foreach ($this->collImagess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCommentss !== null) {
				foreach ($this->collCommentss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCategoriesRelatedByCategoryId !== null) {
				if (!$this->aCategoriesRelatedByCategoryId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCategoriesRelatedByCategoryId->getValidationFailures());
				}
			}

			if ($this->aCategoriesRelatedByCategoryUpcategoryId !== null) {
				if (!$this->aCategoriesRelatedByCategoryUpcategoryId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCategoriesRelatedByCategoryUpcategoryId->getValidationFailures());
				}
			}

			if ($this->asfGuardUser !== null) {
				if (!$this->asfGuardUser->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUser->getValidationFailures());
				}
			}


			if (($retval = AdvicePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collTagss !== null) {
					foreach ($this->collTagss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collImagess !== null) {
					foreach ($this->collImagess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCommentss !== null) {
					foreach ($this->collCommentss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AdvicePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getSlug();
				break;
			case 2:
				return $this->getRating();
				break;
			case 3:
				return $this->getDescription();
				break;
			case 4:
				return $this->getInstruction();
				break;
			case 5:
				return $this->getCreatedAt();
				break;
			case 6:
				return $this->getActive();
				break;
			case 7:
				return $this->getMovie();
				break;
			case 8:
				return $this->getLevel();
				break;
			case 9:
				return $this->getVisited();
				break;
			case 10:
				return $this->getTitle();
				break;
			case 11:
				return $this->getCategoryId();
				break;
			case 12:
				return $this->getCategoryUpcategoryId();
				break;
			case 13:
				return $this->getUserId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AdvicePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getSlug(),
			$keys[2] => $this->getRating(),
			$keys[3] => $this->getDescription(),
			$keys[4] => $this->getInstruction(),
			$keys[5] => $this->getCreatedAt(),
			$keys[6] => $this->getActive(),
			$keys[7] => $this->getMovie(),
			$keys[8] => $this->getLevel(),
			$keys[9] => $this->getVisited(),
			$keys[10] => $this->getTitle(),
			$keys[11] => $this->getCategoryId(),
			$keys[12] => $this->getCategoryUpcategoryId(),
			$keys[13] => $this->getUserId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AdvicePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setSlug($value);
				break;
			case 2:
				$this->setRating($value);
				break;
			case 3:
				$this->setDescription($value);
				break;
			case 4:
				$this->setInstruction($value);
				break;
			case 5:
				$this->setCreatedAt($value);
				break;
			case 6:
				$this->setActive($value);
				break;
			case 7:
				$this->setMovie($value);
				break;
			case 8:
				$this->setLevel($value);
				break;
			case 9:
				$this->setVisited($value);
				break;
			case 10:
				$this->setTitle($value);
				break;
			case 11:
				$this->setCategoryId($value);
				break;
			case 12:
				$this->setCategoryUpcategoryId($value);
				break;
			case 13:
				$this->setUserId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AdvicePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setSlug($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setRating($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDescription($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setInstruction($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCreatedAt($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setActive($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setMovie($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setLevel($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setVisited($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setTitle($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setCategoryId($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setCategoryUpcategoryId($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setUserId($arr[$keys[13]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AdvicePeer::DATABASE_NAME);

		if ($this->isColumnModified(AdvicePeer::ID)) $criteria->add(AdvicePeer::ID, $this->id);
		if ($this->isColumnModified(AdvicePeer::SLUG)) $criteria->add(AdvicePeer::SLUG, $this->slug);
		if ($this->isColumnModified(AdvicePeer::RATING)) $criteria->add(AdvicePeer::RATING, $this->rating);
		if ($this->isColumnModified(AdvicePeer::DESCRIPTION)) $criteria->add(AdvicePeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(AdvicePeer::INSTRUCTION)) $criteria->add(AdvicePeer::INSTRUCTION, $this->instruction);
		if ($this->isColumnModified(AdvicePeer::CREATED_AT)) $criteria->add(AdvicePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(AdvicePeer::ACTIVE)) $criteria->add(AdvicePeer::ACTIVE, $this->active);
		if ($this->isColumnModified(AdvicePeer::MOVIE)) $criteria->add(AdvicePeer::MOVIE, $this->movie);
		if ($this->isColumnModified(AdvicePeer::LEVEL)) $criteria->add(AdvicePeer::LEVEL, $this->level);
		if ($this->isColumnModified(AdvicePeer::VISITED)) $criteria->add(AdvicePeer::VISITED, $this->visited);
		if ($this->isColumnModified(AdvicePeer::TITLE)) $criteria->add(AdvicePeer::TITLE, $this->title);
		if ($this->isColumnModified(AdvicePeer::CATEGORY_ID)) $criteria->add(AdvicePeer::CATEGORY_ID, $this->category_id);
		if ($this->isColumnModified(AdvicePeer::CATEGORY_UPCATEGORY_ID)) $criteria->add(AdvicePeer::CATEGORY_UPCATEGORY_ID, $this->category_upcategory_id);
		if ($this->isColumnModified(AdvicePeer::USER_ID)) $criteria->add(AdvicePeer::USER_ID, $this->user_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AdvicePeer::DATABASE_NAME);

		$criteria->add(AdvicePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Advice (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setSlug($this->slug);

		$copyObj->setRating($this->rating);

		$copyObj->setDescription($this->description);

		$copyObj->setInstruction($this->instruction);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setActive($this->active);

		$copyObj->setMovie($this->movie);

		$copyObj->setLevel($this->level);

		$copyObj->setVisited($this->visited);

		$copyObj->setTitle($this->title);

		$copyObj->setCategoryId($this->category_id);

		$copyObj->setCategoryUpcategoryId($this->category_upcategory_id);

		$copyObj->setUserId($this->user_id);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getTagss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTags($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getImagess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addImages($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCommentss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addComments($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Advice Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AdvicePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AdvicePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Categories object.
	 *
	 * @param      Categories $v
	 * @return     Advice The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCategoriesRelatedByCategoryId(Categories $v = null)
	{
		if ($v === null) {
			$this->setCategoryId(NULL);
		} else {
			$this->setCategoryId($v->getId());
		}

		$this->aCategoriesRelatedByCategoryId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Categories object, it will not be re-added.
		if ($v !== null) {
			$v->addAdviceRelatedByCategoryId($this);
		}

		return $this;
	}


	/**
	 * Get the associated Categories object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Categories The associated Categories object.
	 * @throws     PropelException
	 */
	public function getCategoriesRelatedByCategoryId(PropelPDO $con = null)
	{
		if ($this->aCategoriesRelatedByCategoryId === null && ($this->category_id !== null)) {
			$this->aCategoriesRelatedByCategoryId = CategoriesPeer::retrieveByPk($this->category_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCategoriesRelatedByCategoryId->addAdvicesRelatedByCategoryId($this);
			 */
		}
		return $this->aCategoriesRelatedByCategoryId;
	}

	/**
	 * Declares an association between this object and a Categories object.
	 *
	 * @param      Categories $v
	 * @return     Advice The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCategoriesRelatedByCategoryUpcategoryId(Categories $v = null)
	{
		if ($v === null) {
			$this->setCategoryUpcategoryId(NULL);
		} else {
			$this->setCategoryUpcategoryId($v->getCategoryupId());
		}

		$this->aCategoriesRelatedByCategoryUpcategoryId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Categories object, it will not be re-added.
		if ($v !== null) {
			$v->addAdviceRelatedByCategoryUpcategoryId($this);
		}

		return $this;
	}


	/**
	 * Get the associated Categories object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Categories The associated Categories object.
	 * @throws     PropelException
	 */
	public function getCategoriesRelatedByCategoryUpcategoryId(PropelPDO $con = null)
	{
		if ($this->aCategoriesRelatedByCategoryUpcategoryId === null && ($this->category_upcategory_id !== null)) {
			$c = new Criteria(CategoriesPeer::DATABASE_NAME);
			$c->add(CategoriesPeer::CATEGORYUP_ID, $this->category_upcategory_id);
			$this->aCategoriesRelatedByCategoryUpcategoryId = CategoriesPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCategoriesRelatedByCategoryUpcategoryId->addAdvicesRelatedByCategoryUpcategoryId($this);
			 */
		}
		return $this->aCategoriesRelatedByCategoryUpcategoryId;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     Advice The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUser(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getId());
		}

		$this->asfGuardUser = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addAdvice($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUser(PropelPDO $con = null)
	{
		if ($this->asfGuardUser === null && ($this->user_id !== null)) {
			$this->asfGuardUser = sfGuardUserPeer::retrieveByPk($this->user_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUser->addAdvices($this);
			 */
		}
		return $this->asfGuardUser;
	}

	/**
	 * Clears out the collTagss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTagss()
	 */
	public function clearTagss()
	{
		$this->collTagss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTagss collection (array).
	 *
	 * By default this just sets the collTagss collection to an empty array (like clearcollTagss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTagss()
	{
		$this->collTagss = array();
	}

	/**
	 * Gets an array of Tags objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Advice has previously been saved, it will retrieve
	 * related Tagss from storage. If this Advice is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Tags[]
	 * @throws     PropelException
	 */
	public function getTagss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AdvicePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTagss === null) {
			if ($this->isNew()) {
			   $this->collTagss = array();
			} else {

				$criteria->add(TagsPeer::ADVICE_ID, $this->id);

				TagsPeer::addSelectColumns($criteria);
				$this->collTagss = TagsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TagsPeer::ADVICE_ID, $this->id);

				TagsPeer::addSelectColumns($criteria);
				if (!isset($this->lastTagsCriteria) || !$this->lastTagsCriteria->equals($criteria)) {
					$this->collTagss = TagsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTagsCriteria = $criteria;
		return $this->collTagss;
	}

	/**
	 * Returns the number of related Tags objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Tags objects.
	 * @throws     PropelException
	 */
	public function countTagss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AdvicePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTagss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TagsPeer::ADVICE_ID, $this->id);

				$count = TagsPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TagsPeer::ADVICE_ID, $this->id);

				if (!isset($this->lastTagsCriteria) || !$this->lastTagsCriteria->equals($criteria)) {
					$count = TagsPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTagss);
				}
			} else {
				$count = count($this->collTagss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Tags object to this object
	 * through the Tags foreign key attribute.
	 *
	 * @param      Tags $l Tags
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTags(Tags $l)
	{
		if ($this->collTagss === null) {
			$this->initTagss();
		}
		if (!in_array($l, $this->collTagss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTagss, $l);
			$l->setAdvice($this);
		}
	}

	/**
	 * Clears out the collImagess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addImagess()
	 */
	public function clearImagess()
	{
		$this->collImagess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collImagess collection (array).
	 *
	 * By default this just sets the collImagess collection to an empty array (like clearcollImagess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initImagess()
	{
		$this->collImagess = array();
	}

	/**
	 * Gets an array of Images objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Advice has previously been saved, it will retrieve
	 * related Imagess from storage. If this Advice is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Images[]
	 * @throws     PropelException
	 */
	public function getImagess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AdvicePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collImagess === null) {
			if ($this->isNew()) {
			   $this->collImagess = array();
			} else {

				$criteria->add(ImagesPeer::ADVICE_ID, $this->id);

				ImagesPeer::addSelectColumns($criteria);
				$this->collImagess = ImagesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ImagesPeer::ADVICE_ID, $this->id);

				ImagesPeer::addSelectColumns($criteria);
				if (!isset($this->lastImagesCriteria) || !$this->lastImagesCriteria->equals($criteria)) {
					$this->collImagess = ImagesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastImagesCriteria = $criteria;
		return $this->collImagess;
	}

	/**
	 * Returns the number of related Images objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Images objects.
	 * @throws     PropelException
	 */
	public function countImagess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AdvicePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collImagess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ImagesPeer::ADVICE_ID, $this->id);

				$count = ImagesPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ImagesPeer::ADVICE_ID, $this->id);

				if (!isset($this->lastImagesCriteria) || !$this->lastImagesCriteria->equals($criteria)) {
					$count = ImagesPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collImagess);
				}
			} else {
				$count = count($this->collImagess);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Images object to this object
	 * through the Images foreign key attribute.
	 *
	 * @param      Images $l Images
	 * @return     void
	 * @throws     PropelException
	 */
	public function addImages(Images $l)
	{
		if ($this->collImagess === null) {
			$this->initImagess();
		}
		if (!in_array($l, $this->collImagess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collImagess, $l);
			$l->setAdvice($this);
		}
	}

	/**
	 * Clears out the collCommentss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCommentss()
	 */
	public function clearCommentss()
	{
		$this->collCommentss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCommentss collection (array).
	 *
	 * By default this just sets the collCommentss collection to an empty array (like clearcollCommentss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCommentss()
	{
		$this->collCommentss = array();
	}

	/**
	 * Gets an array of Comments objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Advice has previously been saved, it will retrieve
	 * related Commentss from storage. If this Advice is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Comments[]
	 * @throws     PropelException
	 */
	public function getCommentss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AdvicePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCommentss === null) {
			if ($this->isNew()) {
			   $this->collCommentss = array();
			} else {

				$criteria->add(CommentsPeer::ADVICE_ID, $this->id);

				CommentsPeer::addSelectColumns($criteria);
				$this->collCommentss = CommentsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CommentsPeer::ADVICE_ID, $this->id);

				CommentsPeer::addSelectColumns($criteria);
				if (!isset($this->lastCommentsCriteria) || !$this->lastCommentsCriteria->equals($criteria)) {
					$this->collCommentss = CommentsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCommentsCriteria = $criteria;
		return $this->collCommentss;
	}

	/**
	 * Returns the number of related Comments objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Comments objects.
	 * @throws     PropelException
	 */
	public function countCommentss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AdvicePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCommentss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CommentsPeer::ADVICE_ID, $this->id);

				$count = CommentsPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CommentsPeer::ADVICE_ID, $this->id);

				if (!isset($this->lastCommentsCriteria) || !$this->lastCommentsCriteria->equals($criteria)) {
					$count = CommentsPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCommentss);
				}
			} else {
				$count = count($this->collCommentss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Comments object to this object
	 * through the Comments foreign key attribute.
	 *
	 * @param      Comments $l Comments
	 * @return     void
	 * @throws     PropelException
	 */
	public function addComments(Comments $l)
	{
		if ($this->collCommentss === null) {
			$this->initCommentss();
		}
		if (!in_array($l, $this->collCommentss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCommentss, $l);
			$l->setAdvice($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Advice is new, it will return
	 * an empty collection; or if this Advice has previously
	 * been saved, it will retrieve related Commentss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Advice.
	 */
	public function getCommentssJoinsfGuardUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AdvicePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCommentss === null) {
			if ($this->isNew()) {
				$this->collCommentss = array();
			} else {

				$criteria->add(CommentsPeer::ADVICE_ID, $this->id);

				$this->collCommentss = CommentsPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CommentsPeer::ADVICE_ID, $this->id);

			if (!isset($this->lastCommentsCriteria) || !$this->lastCommentsCriteria->equals($criteria)) {
				$this->collCommentss = CommentsPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastCommentsCriteria = $criteria;

		return $this->collCommentss;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collTagss) {
				foreach ((array) $this->collTagss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collImagess) {
				foreach ((array) $this->collImagess as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCommentss) {
				foreach ((array) $this->collCommentss as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collTagss = null;
		$this->collImagess = null;
		$this->collCommentss = null;
			$this->aCategoriesRelatedByCategoryId = null;
			$this->aCategoriesRelatedByCategoryUpcategoryId = null;
			$this->asfGuardUser = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseAdvice:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseAdvice::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseAdvice
